import { api } from './api'

/**
 * Finance service to handle data operations (Model).
 * Decouples API logic from components.
 */

const FRANKFURTER_SUPPORTED = new Set([
  'EUR','GBP','JPY','CHF','CAD','AUD','CNY','HKD','NZD','SEK','NOK','DKK',
  'MXN','BRL','HUF','PLN','CZK','RON','BGN','ISK','IDR','INR','ILS','KRW',
  'MYR','PHP','SGD','THB','TRY','ZAR',
])

export const financeService = {
  /**
   * Fetches the latest exchange rates relative to USD.
   */
  getLatestRates: async () => {
    return await api.get('https://open.er-api.com/v6/latest/USD')
  },

  /**
   * Fetches historical rates for the given currency pair and start date.
   */
  getHistoricalRates: async (from, to, startDate) => {
    const today = new Date().toISOString().split('T')[0]
    
    // Check if Frankfurter supports this pair
    const canUseAPI = (from === 'USD' || FRANKFURTER_SUPPORTED.has(from)) && 
                     (to === 'USD' || FRANKFURTER_SUPPORTED.has(to)) && 
                     from !== to

    if (canUseAPI) {
      try {
        const data = await api.get(`https://api.frankfurter.app/${startDate}..${today}?from=${from}&to=${to}`)
        if (data.rates) {
          return Object.entries(data.rates)
            .sort(([a], [b]) => a.localeCompare(b))
            .map(([date, r]) => ({ date, value: r[to] }))
        }
      } catch (error) {
        console.warn('Frankfurter API failed, fallback to synthetic data.', error)
      }
    }
    
    return null // Return null to indicate that synthetic data should be generated by the calling logic
  },

  /**
   * Simulates a transaction (transfer, deposit, withdraw, exchange).
   * Ready for back-end integration.
   */
  performTransaction: async (userId, data) => {
    return await api.post('/transactions', { userId, ...data, timestamp: new Date().toISOString() })
  }
}
